[package]
name = "audit"
version = "0.1.1"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
edition = "2018"

homepage = "https://github.com/little-dude/netlink"
keywords = ["netlink", "ip", "linux", "audit"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/little-dude/netlink"
description = "linux audit via netlink"

[dependencies]
futures = "0.1.25"
lazy_static = "1.2.0"
failure = "0.1.3"

[dependencies.netlink-sys]
version = "0.1"
default-features = false
features = ["tokio_support"]
path = "../netlink-sys"

[dependencies.netlink-packet]
version = "0.1"
default-features = false
features = ["audit"]
path = "../netlink-packet"

[dependencies.netlink-proto]
version = "0.1"
default-features = false
features = ["audit"]
path = "../netlink-proto"

[dev-dependencies]
env_logger = "0.6.0"
tokio-core = "0.1.17"
