name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ci:
    name: CI (stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: test
        run: cargo test -p netlink-sys
